### ISSUE TITLE
Where to download a VM image with installed `x86_64-freebsd`?

### ISSUE THREAD

**Issue by kvtb** [nixos-bsd/nixbsd#35]
... because the derivations require a `x86_64-freebsd` builder and it is not available to download.

I know, there suppose to be a binary cache, but it does not list its files to download, so a user has to try all commit history in hope that some commit will produce a valid hash to download a VM image from the binary cache (e.g. the last commit does not)

**Comment by rhelmot** [comment]
Gonna comment on this even though you closed it in case someone else has the same question in the future:

You can actually build most things cross. The flake output `packages.x86_64-linux.base.vm` will give you an image of a FreeBSD system that you can run from a Linux host. 

At this exact moment, the binary cache is a little bit sparse because we've been doing active development. We were actually just talking last night about getting CI up and running to automatically populate the cache, but that's a task for another day. 

Last I checked, the only thing that couldn't be built cross was the graphical system, and I think that one has rotted to the point it won't build native either...

**Comment by kvtb** [comment]
I managed to compile Nix on vanilla FreeBSD thus creating a `x86_64-freebsd` remote builder.
It is able to build some derivations (e.g. `pkgs.hello`), but still fails on many others

**Comment by artemist** [comment]
The stdenv has only been tested with sandboxing enabled, which is not upstream. We have a prototype sandboxed lix that still needs a bit of cleanup before it can be submitted: https://git.lix.systems/artemist/lix/src/branch/freebsd-build
